[package]
name = "nuhope-exec"
version = "0.1.0"
authors = ["Lukas Prokop <lukas.prokop@iaik.tugraz.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuhope = { path = "../nuhope" }